name: test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [ 21 ]
        os: [ ubuntu ]
    steps:
      - name: Check out repo
        uses: actions/checkout@v4.2.2
      - name: Set up java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
      - name: Cache Gradle
        uses: actions/cache@v4.2.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Run Gradle's test task
        run: ./gradlew --no-daemon --parallel --continue --build-cache --stacktrace test
